### ISSUE TITLE
Log menu startup state doesn't match real state of the log window

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#27]
When started, the log window is shown as part of the maim window. In menu View/show application log is not checked. If selected, the menu item switches to checked status, but nothing happens with with the window. Further on, the menu switch works as expected, switching the log window together with the menu item check sign.

**Comment by fvacek** [comment]
fixed

**Comment by Amaroun** [comment]
Still doesn't work, the window often starts with view/application log item checked, but without visible log window. Althoug I must say I do remember seeing QE started in correct configuration, I'm not able to do it any more.

**Comment by fvacek** [comment]
Have you tried last sources? It is working for me. I've dropped feature when Log window remembers last state and QE always starts with Log Dock hidden but check should show proper state
