### ISSUE TITLE
results XML export doesn't contain next split after the missing one

### ISSUE THREAD

**Issue by zprecek** [fvacek/quickbox#387]
![pgp1052-oris](https://user-images.githubusercontent.com/9889605/57067619-ccb5b000-6ccf-11e9-8a3a-f9f47083322b.png)
![pgp1052](https://user-images.githubusercontent.com/9889605/57037280-0c8c8100-6c57-11e9-87d5-48214a729cdb.png)
[pgp1052.txt](https://github.com/fvacek/quickbox/files/3135730/pgp1052.txt)
In the attached example we can see, that punching from control 6 is missing in the XML export although it has been read from the SI card.
As a result, the receiver of the export (ORIS in this case) is unable to compute one more split time next to the really missing one.

**Comment by fvacek** [comment]
same problem in Havlikuv Brod 
[sprint-poza_2.qbe.zip](https://github.com/fvacek/quickbox/files/3170415/sprint-poza_2.qbe.zip)

**Comment by fvacek** [comment]
affected export versions: IOF-XML2.3 and IOF-XML3.0

**Comment by fvacek** [comment]
This cannot be fixed easily due to card preprocessing design. Only punches with valid lap-time are stored in the `runlaps` table. I agree that this is a design fault and this is also something what shall be fixed in future but we have more serious bugs for now. There are two possible solutions:
1. save also punches with valid stp-time but invalid lap-time to to the `runlaps` table
1. take data for export from `cards` table directly

**Comment by fvacek** [comment]
fixed in 2.2.6

**Comment by zprecek** [comment]
Checked in 2.2.6.
Apparently not fixed, indeed.
The issue is still there in both v2.3 and v3.0 IOF-XML exports.

**Comment by paukert** [comment]
If you were not organising event on 2.2.6, try "Load times from card in selected rows" option in Runs plugin or "Recalculate times in selected rows" in Card reader plugin.

**Comment by zprecek** [comment]
Well, that's the case.
The event has been processed in quickevent ver. 2.2.2.
Thank you for hint. "Load times from card in selected rows"  in 2.2.6 fixed the issue.
